### ISSUE TITLE
Code update: installation and running errors

### ISSUE THREAD

**Issue by am401** [tuladhar/multi-threaded-google-ban-checker#5]
# Issue
Hello there! While trying to look at getting the application running in order to help contribute to the existing issues raised I ran in to a couple of bugs. I was able to resolve these and get the script running, albeit I haven't had a chance to fully test the entire scripts functionality as I do not have access to password protected proxies.

# urlparse module rename

> Note The urlparse module is renamed to urllib.parse in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3.

As noted above on the [Python 2 urlparse documentation](https://docs.python.org/2/library/urlparse.html), within the header, the module was renamed. The error I ran into was:

```
python3 main.py
No module named 'urlparse'

try installing the missing module using: pip install <module>
note: helper.useragent, helper.keywords, helper.proxy are custom modules and can't be installed via pip.
```

Trying to see how I could get the module working lead me to the Python 2 documentation I have referenced above and I was able to adjust https://github.com/tuladhar/multi-threaded-google-ban-checker/blob/d3bb112165c8af911a3b18811497d27e5bb94f9d/main.py#L40 to:

```
from urllib.parse import urlparse
```

The above code resolved the module issue and I was able to attempt to run the application.

# Documentation error

While trying to follow the documentation I noticed the installation instructions showed the following in order to output the `PROXIES.txt` file content to be read by `main.py`:

```
$ cat PROXIES.txt > python main.py --realtime
```

In the above line `>` redirects the output of `cat PROXIES.txt` as opposed to pipes the output to be used. What ends up happening is it creates a file called `python3` which essentially ends up with the content of both `PROXIES.txt` and `main.py` and shows an error with regards to the `-R` flag:

```
$ cat PROXIES.txt > python3 main.py -R
cat: -R: No such file or directory
# cat python3
admin:password@219.250.23.243:8888
administrator:pass@5.58.50.5:8080
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```

To adjust the above - we need to replace `>` by `|` which will pipe the output of the first command (`cat`) in to the second command (`python3 main.py`).

# TypeError
Once I got the piping resolved, I found another bug:

```
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    num_proxies = len(proxies)
TypeError: object of type 'filter' has no len()
```

Research on the above indicates that `len()` cannot be used directly on `filter()` as noted [here](https://stackoverflow.com/questions/24291604/find-the-length-of-a-filter-object-in-python-3/24291674#24291674):

> In Python2.x, filter is returning a list, but in Python3 it is giving you an iterator which you can convert to a list and then check the length

In order to resolve the above issue, I wrapped a list around the `filter()` as recommended here https://github.com/tuladhar/multi-threaded-google-ban-checker/blob/d3bb112165c8af911a3b18811497d27e5bb94f9d/main.py#L189

```
proxies = list(filter(helper.proxy.is_valid, all_proxies))
```

# Summary
With the above changes I was able to get the application running against a test list and no errors were noted. I have created a PR with the changes made.

**Comment by am401** [comment]
PR #6 created to resolve the above identified issues

**Comment by tuladhar** [comment]
This is great. Thank you very much @am401
